# Generated by Django 2.1 on 2019-06-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20190605_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
