# Generated by Django 2.1 on 2019-06-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.URLField(blank=True, default='ulr'),
        ),
    ]
