# Generated by Django 2.1 on 2019-06-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190618_0244'),
        ('articles', '0003_auto_20190617_1248'),
    ]

    operations = [
    ]
