# Generated by Django 2.1 on 2019-06-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190617_1248'),
        ('articles', '0003_auto_20190617_1214'),
    ]

    operations = [
    ]
