# Generated by Django 2.1 on 2019-06-19 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_merge_20190618_0923'),
        ('articles', '0004_merge_20190618_1311'),
    ]

    operations = [
    ]
