# Generated by Django 2.1 on 2019-06-20 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_merge_20190619_1232'),
        ('articles', '0004_merge_20190619_1100'),
    ]

    operations = [
    ]
