# Generated by Django 2.1 on 2019-06-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_tagging', '0001_initial'),
        ('articles', '0005_merge_20190619_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tagNames',
            field=models.ManyToManyField(related_name='articles', to='article_tagging.ArticleTagging'),
        ),
    ]
