# Generated by Django 2.1 on 2019-06-20 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_tagnames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tagNames',
            new_name='tagName',
        ),
    ]
