# Generated by Django 2.1 on 2019-06-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20190620_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tagName',
            field=models.ManyToManyField(blank=True, related_name='articles', to='article_tagging.ArticleTagging'),
        ),
    ]
