# Generated by Django 2.1 on 2019-06-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20190620_1603'),
        ('articles', '0006_merge_20190620_0849'),
    ]

    operations = [
    ]
